name: simple workflow
on: [workflow_dispatch, push]
jobs:
  example:
    name: Ari's example job
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: echo "I am an echo"

      - id: save-variable
        run: echo "text='Jobs done!'" >> $GITHUB_OUTPUT

      - name: Save job output
        run: echo "${{ steps.save-variable.outputs.text }}" >> $GITHUB_STEP_SUMMARY
